#!/bin/zsh

#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export PROJECT_HOME="$HOME/Developer"
# Ensure that all new environments are isolated from the system site-packages directory.
# export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--no-site-packages'