#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
# Source Zsh framework.
if [[ -s "${ZDOTDIR:-$HOME}/.zsh/init.zsh" ]]
then
    source "${ZDOTDIR:-$HOME}/.zsh/init.zsh"
fi

# Customize to your needs...
