#!/bin/zsh

##
#  @file
#
#  @brief Executes commands at the start of an interactive session.
#
#  @author
#      Sorin Ionescu <sorin.ionescu@gmail.com>
#      Martin Zeman <https://github.com/N4M3Z>
#

# Measure elapsed time
typeset -F SECONDS

# Debug
# set -x

# Source Prezto framework.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]
then
    source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Private tokens
# export SSH_KEY_PATH="~/.ssh/dsa_id"
if [[ -s "${ZDOTDIR:-$HOME}/.private" ]]
then
    source "${ZDOTDIR:-$HOME}/.private"
fi

# Print elapsed time
echo "${SECONDS}s elapsed"
