#!/bin/zsh

##
#  @file
#       is-osx
#
#  @brief
#       Check whether a command is defined
#
#  @author
#      Martin Zeman <https://github.com/N4M3Z>

function is-defined ()
{
    type "$1" &> /dev/null;
}
