#!/bin/zsh

##
#  @file
#
#  @brief
#      Common download functions
#
#  @author
#      N4M3Z <https://github.com/N4M3Z>

function zsh-core-update()
{
    cd "${ZDOTDIR:-$HOME}/.zpreztorc"
    git pull
    git submodule update --init --recursive
}
