#!/bin/zsh

##
#  @file
#      zsh-core-setup
#  @brief
#      Common functions
#
#  @author
#      N4M3Z <https://github.com/N4M3Z>
#
#  @note
#      Based on oh-my-zsh plugin zsh_reload
#
function zsh-core-reset()
{
    local cache=$ZSH_CACHE_DIR
    autoload -U compinit zrecompile
    compinit -d "$cache/zcomp-$HOST"

    for f in ~/.zshrc "$cache/zcomp-$HOST"; do
      zrecompile -p $f && command rm -f $f.zwc.old
    done

    zsh.setup
}
