#!/bin/zsh

function pip-install()
{
    pip install --upgrade pip
    pip install --upgrade setuptools
    pip install --upgrade argparse
    pip install --upgrade mercurial
    pip install --upgrade powerline-status
    pip install --upgrade Pygments
}
