#!/bin/zsh

##
#  @file
#       .zgen
#  @brief
#       zgen initialization.
#
#  @author
#       Martin Zeman <martin.zeman@protonmail.ch>
#
#  @note
#       Uses tarjoilija/zgen plugin manager which is a simplified version of zsh-users/antigen
#

##
# Example
#
zgen load robbyrussell/oh-my-zsh themes/jonathan.zsh-theme
